title: Guts Blog
description: My GitHub Pages Development Blog

url: "https://ehdtn3540.github.io"
baseurl: "/guts-blog"

# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

